# This file configures Netlify's build and redirect settings.

# --- Build Settings ---
# Specifies the build command and the directory where the built files are located.
[build]
  base    = "client" # The directory where the build command should be run
  command = "npm run build" # The command to build the site
  publish = "client/dist" # The directory to publish

# --- Redirects and Rewrites ---

# Proxy API requests to the backend server on Render.
[[redirects]]
  from = "/api/*"
  to = "https://mern-stack-integration-masmunge95.onrender.com/api/:splat"
  status = 200 # Rewrite rule (proxy)

# Proxy image uploads to the backend server.
[[redirects]]
  from = "/uploads/*"
  to = "https://mern-stack-integration-masmunge95.onrender.com/uploads/:splat"
  status = 200 # Rewrite rule (proxy)

# SPA fallback: Redirect all other requests to index.html for client-side routing.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    # Add any custom headers here. For example, Content Security Policy.