# Netlify configuration for the MERN Blog project

[build]
  # This is the directory where Netlify will run the build command.
  base = "client"
  # This is the command Netlify will run to build your frontend.
  command = "npm run build"
  # This is the directory that contains the built assets, relative to the 'base' directory.
  publish = "dist"

# Proxy API requests to your backend server on Render.
[[redirects]]
  from = "/api/*"
  to = "https://mern-stack-integration-masmunge95.onrender.com/api/:splat"
  status = 200

# SPA fallback: Redirect all other requests to index.html so client-side routing works.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add Content Security Policy headers to allow Clerk scripts and frames.
[[headers]]
  for = "/*"
  [headers.values]
    # More comprehensive Content Security Policy for production
    script-src = "'self' 'unsafe-inline' https://working-toucan-66.clerk.accounts.dev https://*.google.com https://*.gstatic.com https://challenges.cloudflare.com https://*.cloudflare.com"
    connect-src = "'self' https://working-toucan-66.clerk.accounts.dev https://clerk-telemetry.com https://mern-stack-integration-masmunge95.onrender.com https://*.google.com https://challenges.cloudflare.com https://*.cloudflare.com"
    frame-src = "'self' https://working-toucan-66.clerk.accounts.dev https://*.google.com https://challenges.cloudflare.com https://*.cloudflare.com"
    style-src = "'self' 'unsafe-inline' https://working-toucan-66.clerk.accounts.dev https://fonts.googleapis.com"
    # Add Permissions-Policy headers to silence warnings
    Permissions-Policy = "browsing-topics=(), interest-cohort=()"
